package vn.futaland.app.core.i18n

import android.content.Context
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import java.text.Normalizer
import java.util.Locale
import java.util.concurrent.ConcurrentHashMap

/**
 * In-app display language, mirroring the web's language switcher (`bds-clone/src/i18n`) and iOS
 * `AppLanguage`. The choice is stored under the same key as the web/iOS (`app-language`).
 */
enum class AppLanguage(val code: String, val displayName: String, val locale: Locale) {
    VI("vi", "Tiếng Việt", Locale("vi", "VN")),
    EN("en", "English", Locale("en", "US")),
    ZH("zh", "中文", Locale.SIMPLIFIED_CHINESE),
    RU("ru", "Русский", Locale("ru", "RU")),
    KO("ko", "한국어", Locale("ko", "KR"));

    companion object {
        fun fromCode(code: String?): AppLanguage = entries.firstOrNull { it.code == code } ?: VI
    }
}

/**
 * UI strings are Vietnamese literals; their translations are keyed by the Vietnamese sentence in
 * `assets/i18n/<language>.json`, generated by `scripts/generate-localizations.mjs` from the web
 * dictionaries and the iOS/Android supplements. [translate] is applied at display time (the app's
 * [Text] wrapper, toasts), so literals, ternaries and API labels all follow the switcher.
 * Interpolated sentences go through `tr("Đã chọn {0} mục", n)`.
 *
 * Changing the language recreates the activity (see [LanguagePicker]), like iOS re-identifying its root.
 */
object I18n {
    const val STORAGE_KEY = "app-language"
    private const val PREFS = "futaland_app_settings"

    @Volatile
    var language: AppLanguage = AppLanguage.VI
        private set

    /** Set before a language change recreates the activity, so the account tab opens again (iOS parity). */
    @Volatile var reopenAccountTab = false

    @Volatile private var table: Map<String, String> = emptyMap()
    @Volatile private var caseless: Map<String, String> = emptyMap()
    private val memo = ConcurrentHashMap<String, String>()
    private lateinit var appContext: Context

    /** Call from `Application.onCreate` before any UI is shown. */
    fun init(context: Context) {
        appContext = context.applicationContext
        val stored = appContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(STORAGE_KEY, null)
        load(AppLanguage.fromCode(stored))
    }

    /** Stores and loads [newLanguage]; the caller recreates the activity so every screen re-renders. */
    fun setLanguage(newLanguage: AppLanguage) {
        appContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
            .putString(STORAGE_KEY, newLanguage.code).apply()
        load(newLanguage)
    }

    private fun load(newLanguage: AppLanguage) {
        val entries: Map<String, String> = if (newLanguage == AppLanguage.VI) emptyMap() else try {
            val raw = appContext.assets.open("i18n/${newLanguage.code}.json").bufferedReader().use { it.readText() }
            (Json.parseToJsonElement(raw) as JsonObject).mapValues { (it.value as JsonPrimitive).content }
        } catch (_: Exception) {
            emptyMap()
        }
        val lower = HashMap<String, String>(entries.size)
        for ((key, value) in entries) lower.putIfAbsent(key.lowercase(VI_LOCALE), value)
        memo.clear()
        table = entries
        caseless = lower
        language = newLanguage
    }

    /** [text] in the in-app language; unchanged when there is no translation (and always in Vietnamese). */
    fun translate(text: String): String {
        if (language == AppLanguage.VI || text.isBlank()) return text
        memo[text]?.let { return it }
        val result = lookup(text) ?: lookupLines(text) ?: text
        if (memo.size < 20_000) memo[text] = result
        return result
    }

    /** Template with `{0}`, `{1}`… placeholders, translated, then filled with [args]. */
    fun format(template: String, vararg args: Any?): String {
        var result = translate(template)
        args.forEachIndexed { index, arg -> result = result.replace("{$index}", arg?.toString() ?: "") }
        return result
    }

    private fun lookup(text: String): String? {
        find(text)?.let { return it }
        // `"SỐ ĐIỆN THOẠI:"` ↔ `"Số điện thoại"`: same tolerances as the generator's audit.
        val trimmed = text.trim()
        val match = SUFFIX.find(trimmed)
        val core = if (match != null && match.range.first > 0) trimmed.substring(0, match.range.first) else trimmed
        if (core == text || core.isEmpty()) return null
        val value = find(core) ?: return null
        val lead = text.substring(0, text.indexOf(trimmed))
        val trail = text.substring(lead.length + core.length)
        return lead + value + trail
    }

    /** Multi-line texts built from known lines (`"Hotline: …\nĐịa chỉ: …"`). */
    private fun lookupLines(text: String): String? {
        if (!text.contains('\n')) return null
        var changed = false
        val lines = text.split('\n').map { line -> lookup(line)?.also { changed = true } ?: line }
        return if (changed) lines.joinToString("\n") else null
    }

    private fun find(text: String): String? {
        table[text]?.let { return it }
        val normalized = Normalizer.normalize(text, Normalizer.Form.NFC)
        if (normalized != text) table[normalized]?.let { return it }
        val loose = caseless[normalized.lowercase(VI_LOCALE)] ?: return null
        if (normalized == normalized.uppercase(VI_LOCALE)) return loose.uppercase(language.locale)
        val first = normalized.first()
        return if (first.isUpperCase()) loose.replaceFirstChar { it.titlecase(language.locale) } else loose
    }

    private val VI_LOCALE = Locale("vi")
    private val SUFFIX = Regex("""(\s*(?::|\(\*\)|\*|…|\.\.\.|\?|!)\s*|\s+)$""")
}

/** [text] in the in-app language (display-time lookup keyed by the Vietnamese sentence). */
fun tr(text: String): String = I18n.translate(text)

/** Interpolated sentence: `tr("Đã chọn {0} mục", count)`. */
fun tr(template: String, vararg args: Any?): String = I18n.format(template, *args)

/**
 * A word whose meaning depends on the screen ("Nam" = South or Male): looked up by a dedicated
 * [key] (`direction.south`, `gender.male`…), falling back to the Vietnamese [vietnamese].
 */
fun trKey(key: String, vietnamese: String): String {
    if (I18n.language == AppLanguage.VI) return vietnamese
    val value = I18n.translate(key)
    return if (value == key) vietnamese else value
}
